// src/Component/truths.js
const truths = [
  "क्या तुमने कभी किसी को फेस-टू-फेस आई लव यू बोला है?",
"क्या तुमको कभी किसी से ब्रेकअप करने का पछतावा हुआ है?",
"क्या तुमको कभी किसी से फेक रिलेशन में रहना पड़ा है?",
"क्या तुमको कभी किसी पर ओवर क्रश हुआ है?",
  "What’s your most embarrassing memory?",
  "Have you ever had a crush on someone here?",
  "What’s the craziest lie you told your parents?",
  "What is your guilty pleasure?",
  "Have you ever cheated in an exam?",
  "What's your secret talent?",
  "What's the weirdest dream you've ever had?",
  "Who was your first crush?",
  "What's your biggest fear?",
  "Have you ever lied to your best friend?",
  "Who in this group do you have a secret crush on?",
"What’s the most embarrassing thing you’ve ever texted?",
"Who was your first kiss, and how was it?",
"Have you ever lied to get out of trouble?",
"What’s your most useless hidden talent?",
"Have you ever peed in a swimming pool?",
"Which teacher do/did you secretly find hot?",
"Have you ever cheated in an exam?",
"What’s the most childish thing you still do?",
"Who here do you stalk the most on social media?",
"What’s the weirdest dream you’ve ever had?",
"Have you ever pretended to be sick to skip class?",
"Who in this group would you date if you had to?",
"What’s your most awkward romantic experience?",
"Have you ever been caught picking your nose?",
"Who is your celebrity crush?",
"Have you ever kissed someone of the same gender?",
"Who in this group is the funniest?",
"Have you ever cried in public?",
"What’s the worst lie you’ve ever told?",
"What’s the strangest rumor you’ve heard about yourself?",
"Have you ever skipped bathing for more than 3 days?",
"Who was your first crush?",
"What’s the most awkward date you’ve been on?",
"What’s your guilty pleasure song?",
"Have you ever stalked your ex?",
"What’s the weirdest food combo you like?",
"Have you ever farted loudly in class?",
"Who here do you trust the least?",
"Have you ever been rejected by someone you liked?",
"Who in this room would you never want to date?",
"What’s the most disgusting habit you have?",
"Have you ever stolen something?",
"Who here do you think is the best kisser?",
"Have you ever had a crush on your best friend’s sibling?",
"Have you ever sent a text to the wrong person?",
"What’s the worst pickup line you’ve ever used/heard?",
"Have you ever gotten into trouble with the police?",
"Who here do you think gossips the most?",
"Have you ever fallen asleep in class?",
"What’s your biggest regret?",
"Have you ever accidentally insulted someone?",
"Who in this room is the best dressed?",
"What’s the craziest excuse you’ve given to skip something?",
"Who here do you think is the biggest drama queen/king?",
"Have you ever fallen in love?",
"Have you ever lied to your parents about where you were going?",
"Who here would you call if you were in trouble at 3 AM?",
"What’s the dumbest way you’ve hurt yourself?",
"Who here do you think is the most attractive?",
"Have you ever kissed more than one person in a day?",
"Have you ever faked being sober?",
"What’s the strangest thing you’ve Googled?",
"Have you ever lied in this game?",
"Who here do you think is most likely to marry rich?",
"Have you ever broken something and blamed someone else?",
"Who here is most likely to go viral online?",
"What’s your wildest fantasy?",
"Who here do you think is most likely to keep secrets?",
"What’s your most embarrassing nickname?",
"Have you ever gotten caught cheating on a test?",
"Who here do you think is most likely to run away for love?",
"What’s your most awkward moment with your crush?",
"Who here do you think would survive a zombie apocalypse?",
"What’s the craziest thing you’ve ever done on a dare?",
"Who here do you think has the weirdest habits?",
"Have you ever told a secret you swore you wouldn’t?",
"Who here would you switch lives with for a day?",
"What’s your biggest insecurity?",
"Who here would you prank the hardest?",
"Have you ever had a crush on a teacher?",
"Who here do you think is most likely to become famous?",
"What’s your weirdest obsession?",
"Who here do you think has the best smile?",
"Have you ever been caught lying?",
"Who here do you think is the laziest?",
"Have you ever accidentally liked an old post while stalking someone?",
"Who here would you most want to be stuck on an island with?",
"What’s the craziest lie you told your parents?",
"Who here do you think is most likely to get arrested?",
"Have you ever cried for no reason?",
"Who here would you not want to be your sibling?",
"What’s your most embarrassing moment in college?",
"Who here is the best dancer?",
"Have you ever pretended to like a gift you hated?",
"Who here do you think would be the worst roommate?",
"What’s the most disgusting food you’ve eaten?",
"Who here do you think is the most innocent?",
"Have you ever had a crush on two people at once?",
"Who here do you think spends the most time on their phone?",
"What’s the most embarrassing thing on your phone?",
"Who here would you most likely go on a road trip with?",
"What’s your most awkward text conversation?",
"Who here is most likely to become a millionaire?",
"What’s the worst haircut you’ve ever had?",
"Who here do you think is the most jealous type?",
"Have you ever lied to impress someone?",
"Who here do you think is the smartest?",
"Have you ever had a wardrobe malfunction?",
"Who here do you think is the best secret keeper?"
];

export default truths;
